<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: xmlrpcuser
 * Date: Sun, 16 Dec 2012 12:10:51 +0100
 */

$conf['title'] = 'test xmlrpc';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['remote'] = 1;
$conf['remoteuser'] = 'xmlrpcuser';

// end auto-generated content
