#!/bin/bash
cpBase=$(cd $(dirname $0); pwd)
java -cp $cpBase/config-1.2.1.jar:$cpBase/scala-library-2.11.1.jar:$cpBase/akka-actor_2.11-2.3.4.jar:$cpBase/guava-15.0.jar:$cpBase/aXMLRPC-1.7.1.jar:$cpBase/jsap-2.1.jar:$cpBase/dokujclient-${pom.version}.jar dw.cli.Program $@
