#!/bin/bash
if [ -L "$0" ] && [ -x $(which greadlink) ]; then
  thisFile="$(greadlink -mn "$0")"
elif [ -L "$0" ] && [ -x $(which readlink) ]; then
  thisFile="$(readlink -mn "$0")"
else
  thisFile="$0"
fi
cpBase="$(dirname "$thisFile")"
java -cp "$cpBase/*" dw.cli.Program $@
